### ISSUE TITLE
Migration details page: pipeline summary text can wrap to multiple lines, should truncate with ellipses/tooltip.

### ISSUE THREAD

**Issue by mturley** [konveyor/forklift-ui#283]
See https://github.com/konveyor/virt-ui/pull/270#issuecomment-736750155

**Comment by mturley** [comment]
@vconzola is this the right solution to this? truncate with ellipses and show the full status summary as a tooltip?

**Comment by vconzola** [comment]
...or not append "Running" to the step name as shown in the mockups.

**Comment by mturley** [comment]
Ah ok sorry. I assumed @gildub did that from a conversation with you. Looks like it came from @fdupont-redhat . We can undo that

**Comment by gildub** [comment]
@vconzola, it effectively came up from a discussion with @fdupont-redhat.
There are two diffents issues at play here:
- The inconsistence between of having a summary "title", like `error` in some cases  as opposed to no "title" when migration is `running`. 
- Besides a bug with the error description displayed, when the step description is added (whether just for error or for running cases too), then wrapping occurs. 

So we need truncate and tooltip in any case.

I'll leave it to you guys to sort out if we prefix or not the summary text with "Running".

**Comment by gildub** [comment]
@mturley,  ellipsis are not kicking in here because the PipelineSummary is not simple text. 
So when using `truncate` it will cut the end of the text without adding ellipsis and the tooltip doesn't trigger either by default.
We can add aTooltip withing the summary but we'd have to customize to get ellipsis.

**Comment by vconzola** [comment]
@gildub I don't have a problem with the inconsistency of not having a title for steps that are running and appending "error" for steps that have failed. Ideally, a title wouldn't be needed it either case and the user would be able to identify the error state by the icon. But for color blind accessibility it's useful to append "error" because to a person unable to distinguish red from green the completed and error pipeline icons will look identical.

**Comment by mturley** [comment]
@vconzola that makes sense to me.

@gildub we can go the custom route, we can probably use the `<TruncatedText>` component I made for that.
