### ISSUE TITLE
Unit/Integration test framework.

### ISSUE THREAD

**Issue by gildub** [konveyor/forklift-ui#320]
For our unit test framework we're going to use React Testing Library which helps to create solid, light unit tests (and eventually integration tests) which we have confidence with.

As we have discussed, Cypress could be used for end to end tests.

**Comment by mturley** [comment]
It'll be interesting to see where we draw the line between our react-testing-library tests and Cypress tests. Even if some of them are redundant it would be nice to have the React-level tests to prevent regressions immediately since they run in CI in this repo, and the Cypress browser-level tests to make sure things really work in a real app image.
