### ISSUE TITLE
Add "expand/collapse all" toggle to the tree view in step 2 of the plan wizard

### ISSUE THREAD

**Issue by mturley** [konveyor/forklift-ui#35]
Currently this is not possible due to a limitation of the PatternFly TreeView. This needs to be solved in PatternFly itself, but I'm opening this issue so we remember to follow up and add that support here once it is available.

**Comment by mturley** [comment]
Upstream issue to track: https://github.com/patternfly/patternfly-react/issues/4797

**Comment by mturley** [comment]
This has now been implemented in PatternFly: https://github.com/patternfly/patternfly-react/pull/5503

**Comment by gildub** [comment]
Following up with https://github.com/patternfly/patternfly-react/issues/5933

**Comment by gildub** [comment]
@mturley , @seanforyou23 ,

Because for the Plan's wizard the top level of Treeview's FilterVMsForm is always a single node "All datacenters" there is no need for a collapse/expand all toggle. 
The default behavior (not sure that was always the case for prior PF core version, but I can't see it in current master and following versions) automatically collapses/expands all sub-nodes when clicking a given node arrow (> or v).
So clicking "All datacenters" node arrow fullfills the requirement to collapse/expand all nodes.

Let me know what you think.

**Comment by mturley** [comment]
Ha! That's a good point, I hadn't considered that we basically already have this functionality. @vconzola do you have an opinion on this? A separate expand/collapse all button for the tree might be overkill.

**Comment by vconzola** [comment]
@mturley I don't like the default behavior if it means that clicking an arrow expands all sub-nodes below it. That's a terrible idea because it doesn't scale well for large trees. I'll bring it up with Matt. I'd like to keep (or go back to) our current design where clicking an arrow only expands the nodes immediately below the selected node. And keep the select all toggle. Can we do this?

**Comment by mturley** [comment]
@vconzola looking into it more closely, it looks like when we passed the `defaultAllExpanded` prop (to make the whole tree start out fully expanded... if we're worried about larger trees, do we still want this behavior?) that causes the expand action to always expand all sub-nodes. That sounds to me like a bug in the TreeView.

However, @gildub now that the TreeView supports the `allExpanded` prop that we can use to implement the expand/collapse-all toggle, I think we can drop `defaultAllExpanded` and just default the `allExpanded` state to true. I'm not sure what the point of that prop is now that the other exists anyway, it seems there's some weird stuff going on with TreeView.

**Comment by mturley** [comment]
Unrelated, @vconzola I really like this new variant they added to the tree view with little dotted-line guides: https://www.patternfly.org/v4/components/tree-view#guides what do you think about switching to that style?

**Comment by vconzola** [comment]
@mturley I like the guides in the tree view too. Let's switch to that style. Wrt having the whole tree fully expanded, for our use case, I'm on the fence. I don't really have a good feel for how many datacenters/clusters a customer will have. When we included hosts in the tree I think full expansion would be problematic, and it might be for folders too. I just don't know what customer environments look like. I guess for now we can keep it as is and change later if it becomes a problem.

**Comment by gildub** [comment]
Guides looks really good.
I adjusted PR accordingly.
Thanks!

**Comment by mturley** [comment]
Leaving this open after #766 so that we can address this after https://github.com/patternfly/patternfly-react/issues/6314 is addressed upstream.

**Comment by mturley** [comment]
This should be fixable by upgrading PF after https://github.com/patternfly/patternfly-react/pull/6326 is released

**Comment by gildub** [comment]
This issue is not relevant anymore as the current design works fine.
With the latest small change from https://github.com/konveyor/forklift-ui/pull/846 only the the children under first level "All datacenters" are initially expanded allowing a reasonable list to be displayed. From there the user can expand manually sub children using the arrow buttons.
