### ISSUE TITLE
Text of network mapping and storage mapping screens

### ISSUE THREAD

**Issue by apinnick** [konveyor/forklift-ui#417]
I suggest the following changes for the network mapping screen and the storage mapping screen.

**Directions**
Current text: `Start with an existing network mapping between your source and target providers, or create a new one.`
Suggested change: "Select an existing network mapping or create a network mapping." 

- The verb for a list is "Select." A user *selects* a list item from the list. "Start with" is not normal usage.
- "Select ... or create ..." is consistent with the text of the General screen, "Select or type to create a namespace".
- The phrase "between your source and target providers" is unnecessary. If the user has created a network mapping in the past, they know what it is for. If they create a new network mapping, there is an explanation.
- Remove the comma after the first option. A list of two options does not require a comma to separate them.
- "create a new one" is vague. Better to call it a mapping instead of "one". The word "new" is redundant if the user is creating a mapping.

**List options**
Current text: One of the options for the mapping list is `Create a new network mapping.`
Suggested change: "Create a network mapping". 
- "New" is redundant.

**New network mapping**
Current text: `Map source and target networks. The default OpenShift pod network is pre-selected. Other networks can be selected in the dropdowns.`
Suggested change: "Select a target network."

- As far as I can see, the user cannot change the source network. "Map source and target networks" implies that the user can do something to the source network.
- Not necessary to say that the default pod network is selected. The user can see this.
- Not necessary to say "Other networks can be selected in the dropdowns". Telling the user to select a target network is sufficient. "Dropdowns" might not be understood by non-English speakers. If you refer to a dropdown list, it is better to call it a list. That is how the IBM style guide refers to this UI element.

**Directions on storage mapping screen**
Current text if a storage mapping is selected: `Map source datastores to target storage classes. Sources missing from your selected mapping have been added. The default storage class is pre-selected. Other storage classes can be selected in the dropdowns.`
Suggested change: "Select an existing storage mapping or create a storage mapping."
- The last two sentences can be omitted for the same reasons mentioned above.

`Sources missing from your selected mapping have been added`
- What does this mean?
- Is there any way for the user to create a mapping that does **not** lack sources?
- Does `sources` refer to source data stores? If so, data stores should be added to make the meaning clearer.
- The existing storage mapping shows more than one source data store. Can a user create a mapping with multiple source data stores? I recall that there was an **Add** button in the past but that seems to have been removed.

**Comment by mturley** [comment]
cc @vconzola

**Comment by mturley** [comment]
@apinnick :

> `Sources missing from your selected mapping have been added`
> * What does this mean?

When the user reaches this step, they have already selected their VMs. So the wizard knows which sources need to be mapped before the user can proceed. If they select an existing mapping (created on the mappings page) that does not include all of those sources, this message appears and those sources are added, leaving the user to select targets for them in addition to what was in the selected mapping.

> * Is there any way for the user to create a mapping that does not lack sources?

Yes, if the user selects an existing mapping that does already cover all of the required sources for the selected VMs, this message does not appear.

> * Does sources refer to source data stores? If so, data stores should be added to make the meaning clearer.

Yes, sources refers to VMware datastores (in the case of storage mappings) and VMware networks (in the case of network mappings). The term "source" was used because it's generic and can be the same in both steps. But we can change it so it says "datastores" and "networks" respectively.

> * The existing storage mapping shows more than one source data store. Can a user create a mapping with multiple source data stores? I recall that there was an Add button in the past but that seems to have been removed.

The Add button is present only when the user is creating a mapping on the mappings page. This is because in that context, the VMs being migrated are not known, so they have all sources in the provider available to them. In the plan wizard, we know exactly which sources are needed to migrate the selected VMs, so they have been added for the user and there is nothing to gain by adding more. If multiple source datastores are needed, they will be shown. The user can create a mapping with any number of source datastores from the mappings page.

**Comment by vconzola** [comment]
@apinnick 
> Current text: `Start with an existing network mapping between your source and target providers, or create a new one.`
> Suggested change: "Select an existing network mapping or create a network mapping."
The reason this is written the way it is is because the user isn't really selecting a network mapping and that's it. Mappings are templates that can be modified for each plan, so essentially when a user chooses to start with an existing mapping they're copying the contents of the mapping into the plan and then editing as necessary. I wanted to call them mapping templates, but that idea was nixed by PM. So, if there's a better way to describe what's actually happening than "Start with..." I welcome ideas.

>The phrase "between your source and target providers" is unnecessary.
Agree.

>Current text: Map source and target networks. The default OpenShift pod network is pre-selected. Other networks can be >selected in the dropdowns.
>Suggested change: "Select a target network."
I'll rework this, but I want to give the user more explanation than just "Select a target network". I want them to know why the pod-network has been pre-selected (it's the default if no other OCP provider networks are chosen) and that they have an option to change it. Same for storage mappings.

>"New" is redundant.
Agree. I'll remove this throughout.

**Comment by apinnick** [comment]
@vconzola 
> The reason this is written the way it is is because the user isn't really selecting a network mapping and that's it. Mappings are templates that can be modified for each plan, so essentially when a user chooses to start with an existing mapping they're copying the contents of the mapping into the plan and then editing as necessary. I wanted to call them mapping templates, but that idea was nixed by PM. So, if there's a better way to describe what's actually happening than "Start with..." I welcome ideas.

Got it. Now I understand why you used "Start with..." That was the part that was not clear to me. I think the fact that the user can modify an existing mapping could be made more explicit.

How does this sound?  "You can select an existing network mapping to modify or you can create a new network mapping."

> I want them to know why the pod-network has been pre-selected (it's the default if no other OCP provider networks are chosen) and that they have an option to change it.

I see. What do you think about this? "The OpenShift pod network is the default target network. You can select a different target network from the network list."

**Comment by mturley** [comment]
> How does this sound? "You can select an existing network mapping to modify or you can create a new network mapping."

The weird part is that if they select an existing mapping that already covers the necessary sources, they won't need to (or even be able to) modify it. Also, in the case where they do need to modify it, "modify" doesn't seem like the ideal choice because they aren't free to change whatever they want, they are simply able to fill in the blank targets asked for by the wizard (sources have been modified for them).

Maybe instead, "You can select an existing network mapping or create a new network mapping. If any existing mapping is not sufficient for the selected VMs, you can complete it here." or something like that.

**Comment by apinnick** [comment]
> Maybe instead, "You can select an existing network mapping or create a new network mapping. If any existing mapping is not sufficient for the selected VMs, you can complete it here." or something like that.

@mturley We know that the user can't modify the source part of the mapping, so I'm not sure that "modify" can't be used. If the user selects an existing mapping, you're saying that they can only change the targets? I think that would be enough of a change to use the word "modify".

Would this work? "You can select an existing network mapping, updating the target network if necessary, or create a new network mapping."

**Comment by mturley** [comment]
Ah, true, I forgot you can change those existing target selections. Either of those two suggestions work for me then, I'll leave it to @vconzola . Maybe your initial suggestion is better. "You can select an existing network mapping to modify or you can create a new network mapping."

**Comment by vconzola** [comment]
@mturley I agree. I prefer "You can select an existing network mapping to modify or you can create a new network mapping." I also like @apinnick suggestion of "The OpenShift pod network is the default target network. You can select a different target network from the network list." Do you need updated mockups or can you just make these changes in the code?

**Comment by mturley** [comment]
I can just make the changes directly. Thanks!

**Comment by mturley** [comment]
@apinnick we decided to just remove `Sources missing from your selected mapping have been added`, right? or did you want to replace that with something else after my explanation?

**Comment by apinnick** [comment]
> we decided to just remove Sources missing from your selected mapping have been added, right? or did you want to replace that with something else after my explanation?

@mturley  That's fine with me. No further suggestions.
