### ISSUE TITLE
Add a confirm dialog when clicking Start/Cutover/Restart on a plan

### ISSUE THREAD

**Issue by mturley** [konveyor/forklift-ui#624]
We don't have a confirmation dialog when starting a plan or initiating cutover on a warm migration plan. This feels like an oversight to me, what do you think @vconzola? A simple button click kicks off such a huge long-running thing, it would be annoying as hell to do it by accident.

**Comment by vconzola** [comment]
Starting a long running task (migration/cutover) isn't destructive pre se, so I'm not sure a confirmation is necessary. But I'd like to run this by the M&A designers at our next meeting. Let's table this one for now. Definitely not something we need to squeeze into 2.1 since the user can always cancel the migration if they want.

**Comment by mturley** [comment]
Note: we had discussed putting a warning here in the confirmation modal if there are critical concerns on any of the selected VMs, and perhaps listing those.
